Add solutiions 08-reactivity
js-tasks-ru/vue-20221107_vologzhaninavv pull request #10
Opened 2022-12-18 10:48 UTC by volovv

2022-12-18 10:48 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-12-18 20:24 UTC, ShGKme requested changes
В `08-reactivity/05-reactify` требуется небольшое исправление, нельзя проверять, что значение реф, по наличию свойства `value`.

2022-12-18 20:24 UTC, ShGKme commented on 08-reactivity/05-reactify/utils/reactify.js
>  }
Проверять значение через `arg.value` в общем случае некорректно. Не только `ref`-ы могут иметь свойство `value`. Например, также хранит значение библиотека `ola` при интерполяции. Корректно проверить является ли значением рефом можно через функцию `isRef`. Но здесь получить значение лучше всего через функцию `unref`, которая для рефа возвращает значение рефа, а иначе просто возвращает аргумент как есть.

2022-12-19 04:43 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-12-19 23:16 UTC, ShGKme approved these changes
Принято 👍

2022-12-19 23:17 UTC, merged